/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "USBFS_1.h"
#include "USBFS_1_audio.h"
#include "USBFS_1_cdc.h"
#include "USBFS_1_hid.h"
#include "USBFS_1_midi.h"
#include "USBFS_1_pvt.h"
#include "USBFS_1_cydmac.h"
#include "USBFS_1_msc.h"
#include "Y_Button_aliases.h"
#include "Y_Button.h"
#include "DEBUG_UART.h"
#include "DEBUG_LED_aliases.h"
#include "DEBUG_LED.h"
#include "X_Button_aliases.h"
#include "X_Button.h"
#include "B_Button_aliases.h"
#include "B_Button.h"
#include "A_Button_aliases.h"
#include "A_Button.h"
#include "Start_Button_aliases.h"
#include "Start_Button.h"
#include "Select_Button_aliases.h"
#include "Select_Button.h"
#include "ADC_SAR_Seq_1.h"
#include "X_Axis_aliases.h"
#include "X_Axis.h"
#include "Y_Axis_aliases.h"
#include "Y_Axis.h"
#include "R_Button_aliases.h"
#include "R_Button.h"
#include "L_Button_aliases.h"
#include "L_Button.h"
#include "USBFS_1_Dm_aliases.h"
#include "USBFS_1_Dm.h"
#include "USBFS_1_Dp_aliases.h"
#include "USBFS_1_Dp.h"
#include "DEBUG_UART_IntClock.h"
#include "ADC_SAR_Seq_1_SAR.h"
#include "ADC_SAR_Seq_1_IntClock.h"
#include "ADC_SAR_Seq_1_TempBuf_dma.h"
#include "ADC_SAR_Seq_1_FinalBuf_dma.h"
#include "ADC_SAR_Seq_1_IRQ.h"
#include "ADC_SAR_Seq_1_SAR_Bypass_aliases.h"
#include "ADC_SAR_Seq_1_SAR_Bypass.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

