/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Select_Button_aliases.h"
#include "Select_Button.h"
#include "Start_Button_aliases.h"
#include "Start_Button.h"
#include "A_Button_aliases.h"
#include "A_Button.h"
#include "B_Button_aliases.h"
#include "B_Button.h"
#include "Y_Button_aliases.h"
#include "Y_Button.h"
#include "X_Button_aliases.h"
#include "X_Button.h"
#include "DEBUG_UART.h"
#include "Joystick_Button_aliases.h"
#include "Joystick_Button.h"
#include "DEBUG_UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

